openapi: 3.1.0
info:
  version: 1.0.0
  title: My contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This API allows users to manage contacts by creating, updating, and deleting
    contacts. Each contact contains a name, phone number, email, and other
    personal information, along with the option to upload an image.

tags:
  - name: 'Contacts'
    description:
      Endpoints for managing contacts, including creating, retrieving, updating,
      and deleting contact information.

servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-soy7.onrender.com

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    put:
      $ref: ../swagger/paths/contacts/{id}/put.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    contact:
      $ref: ..\swagger\components\shemas\contact.yaml
    contactAdd:
      $ref: ..\swagger\components\shemas\contactAdd.yaml

  responses:
    '400':
      $ref: ../swagger/components/responses/400.yaml
    '401':
      $ref: ../swagger/components/responses/401.yaml
    '404':
      $ref: ../swagger/components/responses/404.yaml
    '500':
      $ref: ../swagger/components/responses/500.yaml
